### ISSUE TITLE
Browser is freezing

### ISSUE THREAD

**Issue by dominikager** [sbarry50/vue-business-hours#25]
currently the component is freezing in every browser and on every device

**Comment by dominikager** [comment]
okay funny thing, its only broken in the Timezone of Berlin, Vienna and so on.

**Comment by SohrabZ** [comment]
Unfortunately, we have the same issue. Have you found any fix @dominikager? This issue has something to do with DST since it was ok before today.

**Comment by dominikager** [comment]
yep upgrade to latest version ;)
