### ISSUE TITLE
Allow translating Opens and Closes text

### ISSUE THREAD

**Issue by wilokecom** [sbarry50/vue-business-hours#3]
Could you please add opensText and closesText as props (Under formFieldMixin.js)? It's useful for translating 

`    opensText: {
      type: String,
      default: 'Opens',
      required: false
    },
    closesText: {
      type: String,
      default: 'Closes',
      required: false
    }`
Thanks

**Comment by sbarry50** [comment]
Sorry Ive been super busy and haven't had a chance to take a look at this yet. Hopefully this weekend.

**Comment by sbarry50** [comment]
This has been addressed with PR #4. All strings are able to be translated now.
