### ISSUE TITLE
Add an Emit event to Business Hour

### ISSUE THREAD

**Issue by wilokecom** [sbarry50/vue-business-hours#6]
Hi,
Could you please add an emit event like "change" to BusinessHours component?
I'm using your plugin and I can't access the update value.
EG: 

`<business-hours :days="{myDay}">`

If you add change emit to the component, I can do like this 
`<business-hours :days="{myDay}" @change="updateValue" />`
Thanks

**Comment by sbarry50** [comment]
Sorry I've been super busy lately. I'll check out your PR as soon as I get a chance. Thanks.

**Comment by sbarry50** [comment]
I didn't accept your PR due to many other changes to localization, styles, etc. however I added the event emitter you added. Thanks!
