### ISSUE TITLE
Translate day names?

### ISSUE THREAD

**Issue by graker** [sbarry50/vue-business-hours#9]
Hi!

As I see from [BusinessHoursDay](https://github.com/sbarry50/vue-business-hours/blob/master/src/components/BusinessHoursDay.vue) component code, at the moment day names are rendered using `{{ titleCase(day) }}` where `day` is a string prop passed as a field name from `days` object in parent component.

So, while it is up to user to rename `monday`, `tuesday` etc. to their locale versions, it could be difficult to work in case of several languages coexisting on site. So I wonder maybe it is possible to change `titleCase(day)` to a localization call, similar to what is happening to switchOpen, switchClose, etc labels? That way we could have day names available for translation, while having all the same keys in `days` object.

**Comment by sbarry50** [comment]
Sorry I've been super busy. I'll have to put some thought into this when I get a chance. You're welcome to submit a PR in the meantime if you want.

**Comment by sbarry50** [comment]
Thanks for the PR! I added the common US holidays to the localization defaults so folks in the US don't have to pass a localization object just for holidays but other than that everything looked good. Thanks again.

**Comment by sbarry50** [comment]
I'm not familiar with common international holidays so if anyone wants to add any common ones PR's are welcome!
